// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=.js"
// @generated from file sensor/v1/measurement.proto (package sensor.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sensor/v1/measurement.proto.
 */
export const file_sensor_v1_measurement: GenFile = /*@__PURE__*/
  fileDesc("ChtzZW5zb3IvdjEvbWVhc3VyZW1lbnQucHJvdG8SCXNlbnNvci52MSIeCgtUZW1wZXJhdHVyZRIPCgdjZWxzaXVzGAEgASgBIhoKCFByZXNzdXJlEg4KBnBhc2NhbBgBIAEoASIbCghIdW1pZGl0eRIPCgdwZXJjZW50GAEgASgBIhIKA0NPMhILCgNwcG0YASABKAEiFQoEUE0yNRINCgV1Z19tMxgBIAEoASIVCgRQTTEwEg0KBXVnX20zGAEgASgBIhgKCk5vaXNlTGV2ZWwSCgoCZGIYASABKAEiGQoJUmFkaWF0aW9uEgwKBHVyX2gYASABKAEiHQoOQ2FyYm9uTW9ub3hpZGUSCwoDcHBtGAEgASgBIhQKBU96b25lEgsKA3BwYhgBIAEoASIeCg9OaXRyb2dlbkRpb3hpZGUSCwoDcHBiGAEgASgBIiAKD0FpclF1YWxpdHlJbmRleBINCgVpbmRleBgBIAEoAWIGcHJvdG8z");

/**
 * @generated from message sensor.v1.Temperature
 */
export type Temperature = Message<"sensor.v1.Temperature"> & {
  /**
   * @generated from field: double celsius = 1;
   */
  celsius: number;
};

/**
 * Describes the message sensor.v1.Temperature.
 * Use `create(TemperatureSchema)` to create a new message.
 */
export const TemperatureSchema: GenMessage<Temperature> = /*@__PURE__*/
  messageDesc(file_sensor_v1_measurement, 0);

/**
 * @generated from message sensor.v1.Pressure
 */
export type Pressure = Message<"sensor.v1.Pressure"> & {
  /**
   * @generated from field: double pascal = 1;
   */
  pascal: number;
};

/**
 * Describes the message sensor.v1.Pressure.
 * Use `create(PressureSchema)` to create a new message.
 */
export const PressureSchema: GenMessage<Pressure> = /*@__PURE__*/
  messageDesc(file_sensor_v1_measurement, 1);

/**
 * @generated from message sensor.v1.Humidity
 */
export type Humidity = Message<"sensor.v1.Humidity"> & {
  /**
   * @generated from field: double percent = 1;
   */
  percent: number;
};

/**
 * Describes the message sensor.v1.Humidity.
 * Use `create(HumiditySchema)` to create a new message.
 */
export const HumiditySchema: GenMessage<Humidity> = /*@__PURE__*/
  messageDesc(file_sensor_v1_measurement, 2);

/**
 * @generated from message sensor.v1.CO2
 */
export type CO2 = Message<"sensor.v1.CO2"> & {
  /**
   * @generated from field: double ppm = 1;
   */
  ppm: number;
};

/**
 * Describes the message sensor.v1.CO2.
 * Use `create(CO2Schema)` to create a new message.
 */
export const CO2Schema: GenMessage<CO2> = /*@__PURE__*/
  messageDesc(file_sensor_v1_measurement, 3);

/**
 * @generated from message sensor.v1.PM25
 */
export type PM25 = Message<"sensor.v1.PM25"> & {
  /**
   * @generated from field: double ug_m3 = 1;
   */
  ugM3: number;
};

/**
 * Describes the message sensor.v1.PM25.
 * Use `create(PM25Schema)` to create a new message.
 */
export const PM25Schema: GenMessage<PM25> = /*@__PURE__*/
  messageDesc(file_sensor_v1_measurement, 4);

/**
 * @generated from message sensor.v1.PM10
 */
export type PM10 = Message<"sensor.v1.PM10"> & {
  /**
   * @generated from field: double ug_m3 = 1;
   */
  ugM3: number;
};

/**
 * Describes the message sensor.v1.PM10.
 * Use `create(PM10Schema)` to create a new message.
 */
export const PM10Schema: GenMessage<PM10> = /*@__PURE__*/
  messageDesc(file_sensor_v1_measurement, 5);

/**
 * @generated from message sensor.v1.NoiseLevel
 */
export type NoiseLevel = Message<"sensor.v1.NoiseLevel"> & {
  /**
   * @generated from field: double db = 1;
   */
  db: number;
};

/**
 * Describes the message sensor.v1.NoiseLevel.
 * Use `create(NoiseLevelSchema)` to create a new message.
 */
export const NoiseLevelSchema: GenMessage<NoiseLevel> = /*@__PURE__*/
  messageDesc(file_sensor_v1_measurement, 6);

/**
 * @generated from message sensor.v1.Radiation
 */
export type Radiation = Message<"sensor.v1.Radiation"> & {
  /**
   * @generated from field: double ur_h = 1;
   */
  urH: number;
};

/**
 * Describes the message sensor.v1.Radiation.
 * Use `create(RadiationSchema)` to create a new message.
 */
export const RadiationSchema: GenMessage<Radiation> = /*@__PURE__*/
  messageDesc(file_sensor_v1_measurement, 7);

/**
 * @generated from message sensor.v1.CarbonMonoxide
 */
export type CarbonMonoxide = Message<"sensor.v1.CarbonMonoxide"> & {
  /**
   * @generated from field: double ppm = 1;
   */
  ppm: number;
};

/**
 * Describes the message sensor.v1.CarbonMonoxide.
 * Use `create(CarbonMonoxideSchema)` to create a new message.
 */
export const CarbonMonoxideSchema: GenMessage<CarbonMonoxide> = /*@__PURE__*/
  messageDesc(file_sensor_v1_measurement, 8);

/**
 * @generated from message sensor.v1.Ozone
 */
export type Ozone = Message<"sensor.v1.Ozone"> & {
  /**
   * @generated from field: double ppb = 1;
   */
  ppb: number;
};

/**
 * Describes the message sensor.v1.Ozone.
 * Use `create(OzoneSchema)` to create a new message.
 */
export const OzoneSchema: GenMessage<Ozone> = /*@__PURE__*/
  messageDesc(file_sensor_v1_measurement, 9);

/**
 * @generated from message sensor.v1.NitrogenDioxide
 */
export type NitrogenDioxide = Message<"sensor.v1.NitrogenDioxide"> & {
  /**
   * @generated from field: double ppb = 1;
   */
  ppb: number;
};

/**
 * Describes the message sensor.v1.NitrogenDioxide.
 * Use `create(NitrogenDioxideSchema)` to create a new message.
 */
export const NitrogenDioxideSchema: GenMessage<NitrogenDioxide> = /*@__PURE__*/
  messageDesc(file_sensor_v1_measurement, 10);

/**
 * @generated from message sensor.v1.AirQualityIndex
 */
export type AirQualityIndex = Message<"sensor.v1.AirQualityIndex"> & {
  /**
   * @generated from field: double index = 1;
   */
  index: number;
};

/**
 * Describes the message sensor.v1.AirQualityIndex.
 * Use `create(AirQualityIndexSchema)` to create a new message.
 */
export const AirQualityIndexSchema: GenMessage<AirQualityIndex> = /*@__PURE__*/
  messageDesc(file_sensor_v1_measurement, 11);

