// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=.js"
// @generated from file sensor/v1/sensor.proto (package sensor.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { CO2, Humidity, NoiseLevel, PM10, PM25, Pressure, Temperature } from "./measurement_pb.js";
import { file_sensor_v1_measurement } from "./measurement_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sensor/v1/sensor.proto.
 */
export const file_sensor_v1_sensor: GenFile = /*@__PURE__*/
  fileDesc("ChZzZW5zb3IvdjEvc2Vuc29yLnByb3RvEglzZW5zb3IudjEimAEKBkJNRTY4MBItCgt0ZW1wZXJhdHVyZRgBIAEoCzIWLnNlbnNvci52MS5UZW1wZXJhdHVyZUgAEicKCGh1bWlkaXR5GAIgASgLMhMuc2Vuc29yLnYxLkh1bWlkaXR5SAASJwoIcHJlc3N1cmUYAyABKAsyEy5zZW5zb3IudjEuUHJlc3N1cmVIAEINCgttZWFzdXJlbWVudCKNAQoFU0NENDESHQoDY28yGAEgASgLMg4uc2Vuc29yLnYxLkNPMkgAEi0KC3RlbXBlcmF0dXJlGAIgASgLMhYuc2Vuc29yLnYxLlRlbXBlcmF0dXJlSAASJwoIaHVtaWRpdHkYAyABKAsyEy5zZW5zb3IudjEuSHVtaWRpdHlIAEINCgttZWFzdXJlbWVudCKYAQoGQk1FMjgwEi0KC3RlbXBlcmF0dXJlGAEgASgLMhYuc2Vuc29yLnYxLlRlbXBlcmF0dXJlSAASJwoIaHVtaWRpdHkYAiABKAsyEy5zZW5zb3IudjEuSHVtaWRpdHlIABInCghwcmVzc3VyZRgDIAEoCzITLnNlbnNvci52MS5QcmVzc3VyZUgAQg0KC21lYXN1cmVtZW50IlkKBlNEUzAxMRIfCgRwbTI1GAEgASgLMg8uc2Vuc29yLnYxLlBNMjVIABIfCgRwbTEwGAIgASgLMg8uc2Vuc29yLnYxLlBNMTBIAEINCgttZWFzdXJlbWVudCJxCghJQ1M0MzQzNBIqCglub2lzZV9tYXgYASABKAsyFS5zZW5zb3IudjEuTm9pc2VMZXZlbEgAEioKCW5vaXNlX2F2ZxgCIAEoCzIVLnNlbnNvci52MS5Ob2lzZUxldmVsSABCDQoLbWVhc3VyZW1lbnQiMQoDR1BTEgsKA2xhdBgBIAEoARILCgNsb24YAiABKAESEAoIaGVpZ2h0X20YAyABKAFiBnByb3RvMw", [file_sensor_v1_measurement]);

/**
 * @generated from message sensor.v1.BME680
 */
export type BME680 = Message<"sensor.v1.BME680"> & {
  /**
   * @generated from oneof sensor.v1.BME680.measurement
   */
  measurement: {
    /**
     * @generated from field: sensor.v1.Temperature temperature = 1;
     */
    value: Temperature;
    case: "temperature";
  } | {
    /**
     * @generated from field: sensor.v1.Humidity humidity = 2;
     */
    value: Humidity;
    case: "humidity";
  } | {
    /**
     * @generated from field: sensor.v1.Pressure pressure = 3;
     */
    value: Pressure;
    case: "pressure";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message sensor.v1.BME680.
 * Use `create(BME680Schema)` to create a new message.
 */
export const BME680Schema: GenMessage<BME680> = /*@__PURE__*/
  messageDesc(file_sensor_v1_sensor, 0);

/**
 * @generated from message sensor.v1.SCD41
 */
export type SCD41 = Message<"sensor.v1.SCD41"> & {
  /**
   * @generated from oneof sensor.v1.SCD41.measurement
   */
  measurement: {
    /**
     * @generated from field: sensor.v1.CO2 co2 = 1;
     */
    value: CO2;
    case: "co2";
  } | {
    /**
     * @generated from field: sensor.v1.Temperature temperature = 2;
     */
    value: Temperature;
    case: "temperature";
  } | {
    /**
     * @generated from field: sensor.v1.Humidity humidity = 3;
     */
    value: Humidity;
    case: "humidity";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message sensor.v1.SCD41.
 * Use `create(SCD41Schema)` to create a new message.
 */
export const SCD41Schema: GenMessage<SCD41> = /*@__PURE__*/
  messageDesc(file_sensor_v1_sensor, 1);

/**
 * @generated from message sensor.v1.BME280
 */
export type BME280 = Message<"sensor.v1.BME280"> & {
  /**
   * @generated from oneof sensor.v1.BME280.measurement
   */
  measurement: {
    /**
     * @generated from field: sensor.v1.Temperature temperature = 1;
     */
    value: Temperature;
    case: "temperature";
  } | {
    /**
     * @generated from field: sensor.v1.Humidity humidity = 2;
     */
    value: Humidity;
    case: "humidity";
  } | {
    /**
     * @generated from field: sensor.v1.Pressure pressure = 3;
     */
    value: Pressure;
    case: "pressure";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message sensor.v1.BME280.
 * Use `create(BME280Schema)` to create a new message.
 */
export const BME280Schema: GenMessage<BME280> = /*@__PURE__*/
  messageDesc(file_sensor_v1_sensor, 2);

/**
 * @generated from message sensor.v1.SDS011
 */
export type SDS011 = Message<"sensor.v1.SDS011"> & {
  /**
   * @generated from oneof sensor.v1.SDS011.measurement
   */
  measurement: {
    /**
     * @generated from field: sensor.v1.PM25 pm25 = 1;
     */
    value: PM25;
    case: "pm25";
  } | {
    /**
     * @generated from field: sensor.v1.PM10 pm10 = 2;
     */
    value: PM10;
    case: "pm10";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message sensor.v1.SDS011.
 * Use `create(SDS011Schema)` to create a new message.
 */
export const SDS011Schema: GenMessage<SDS011> = /*@__PURE__*/
  messageDesc(file_sensor_v1_sensor, 3);

/**
 * @generated from message sensor.v1.ICS43434
 */
export type ICS43434 = Message<"sensor.v1.ICS43434"> & {
  /**
   * @generated from oneof sensor.v1.ICS43434.measurement
   */
  measurement: {
    /**
     * @generated from field: sensor.v1.NoiseLevel noise_max = 1;
     */
    value: NoiseLevel;
    case: "noiseMax";
  } | {
    /**
     * @generated from field: sensor.v1.NoiseLevel noise_avg = 2;
     */
    value: NoiseLevel;
    case: "noiseAvg";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message sensor.v1.ICS43434.
 * Use `create(ICS43434Schema)` to create a new message.
 */
export const ICS43434Schema: GenMessage<ICS43434> = /*@__PURE__*/
  messageDesc(file_sensor_v1_sensor, 4);

/**
 * @generated from message sensor.v1.GPS
 */
export type GPS = Message<"sensor.v1.GPS"> & {
  /**
   * @generated from field: double lat = 1;
   */
  lat: number;

  /**
   * @generated from field: double lon = 2;
   */
  lon: number;

  /**
   * @generated from field: double height_m = 3;
   */
  heightM: number;
};

/**
 * Describes the message sensor.v1.GPS.
 * Use `create(GPSSchema)` to create a new message.
 */
export const GPSSchema: GenMessage<GPS> = /*@__PURE__*/
  messageDesc(file_sensor_v1_sensor, 5);

