// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=.js"
// @generated from file crypto/v1/encrypted.proto (package crypto.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file crypto/v1/encrypted.proto.
 */
export const file_crypto_v1_encrypted: GenFile = /*@__PURE__*/
  fileDesc("ChljcnlwdG8vdjEvZW5jcnlwdGVkLnByb3RvEgljcnlwdG8udjEiYAoJRW5jcnlwdGVkEg8KB3ZlcnNpb24YASABKA0SEQoJYWxnb3JpdGhtGAIgASgJEgwKBGZyb20YAyABKAwSDQoFbm9uY2UYBCABKAwSEgoKY2lwaGVydGV4dBgFIAEoDGIGcHJvdG8z");

/**
 * @generated from message crypto.v1.Encrypted
 */
export type Encrypted = Message<"crypto.v1.Encrypted"> & {
  /**
   * @generated from field: uint32 version = 1;
   */
  version: number;

  /**
   * @generated from field: string algorithm = 2;
   */
  algorithm: string;

  /**
   * @generated from field: bytes from = 3;
   */
  from: Uint8Array;

  /**
   * @generated from field: bytes nonce = 4;
   */
  nonce: Uint8Array;

  /**
   * @generated from field: bytes ciphertext = 5;
   */
  ciphertext: Uint8Array;
};

/**
 * Describes the message crypto.v1.Encrypted.
 * Use `create(EncryptedSchema)` to create a new message.
 */
export const EncryptedSchema: GenMessage<Encrypted> = /*@__PURE__*/
  messageDesc(file_crypto_v1_encrypted, 0);

