// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=.js"
// @generated from file device/v1/insight.proto (package device.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Encrypted } from "../../crypto/v1/encrypted_pb.js";
import { file_crypto_v1_encrypted } from "../../crypto/v1/encrypted_pb.js";
import type { BME680, GPS, SCD41 } from "../../sensor/v1/sensor_pb.js";
import { file_sensor_v1_sensor } from "../../sensor/v1/sensor_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file device/v1/insight.proto.
 */
export const file_device_v1_insight: GenFile = /*@__PURE__*/
  fileDesc("ChdkZXZpY2UvdjEvaW5zaWdodC5wcm90bxIJZGV2aWNlLnYxIoABCg1JbnNpZ2h0U2Vuc29yEh0KA2dwcxgBIAEoCzIOLnNlbnNvci52MS5HUFNIABIjCgZibWU2ODAYAiABKAsyES5zZW5zb3IudjEuQk1FNjgwSAASIQoFc2NkNDEYAyABKAsyEC5zZW5zb3IudjEuU0NENDFIAEIICgZzZW5zb3IiPQoQRW5jcnlwdGVkSW5zaWdodBIpCgdzZW5zb3JzGAEgAygLMhguZGV2aWNlLnYxLkluc2lnaHRTZW5zb3IiWgoHSW5zaWdodBIoCgZwdWJsaWMYASADKAsyGC5kZXZpY2UudjEuSW5zaWdodFNlbnNvchIlCgdwcml2YXRlGAIgAygLMhQuY3J5cHRvLnYxLkVuY3J5cHRlZGIGcHJvdG8z", [file_crypto_v1_encrypted, file_sensor_v1_sensor]);

/**
 * @generated from message device.v1.InsightSensor
 */
export type InsightSensor = Message<"device.v1.InsightSensor"> & {
  /**
   * @generated from oneof device.v1.InsightSensor.sensor
   */
  sensor: {
    /**
     * @generated from field: sensor.v1.GPS gps = 1;
     */
    value: GPS;
    case: "gps";
  } | {
    /**
     * @generated from field: sensor.v1.BME680 bme680 = 2;
     */
    value: BME680;
    case: "bme680";
  } | {
    /**
     * @generated from field: sensor.v1.SCD41 scd41 = 3;
     */
    value: SCD41;
    case: "scd41";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message device.v1.InsightSensor.
 * Use `create(InsightSensorSchema)` to create a new message.
 */
export const InsightSensorSchema: GenMessage<InsightSensor> = /*@__PURE__*/
  messageDesc(file_device_v1_insight, 0);

/**
 * @generated from message device.v1.EncryptedInsight
 */
export type EncryptedInsight = Message<"device.v1.EncryptedInsight"> & {
  /**
   * @generated from field: repeated device.v1.InsightSensor sensors = 1;
   */
  sensors: InsightSensor[];
};

/**
 * Describes the message device.v1.EncryptedInsight.
 * Use `create(EncryptedInsightSchema)` to create a new message.
 */
export const EncryptedInsightSchema: GenMessage<EncryptedInsight> = /*@__PURE__*/
  messageDesc(file_device_v1_insight, 1);

/**
 * @generated from message device.v1.Insight
 */
export type Insight = Message<"device.v1.Insight"> & {
  /**
   * @generated from field: repeated device.v1.InsightSensor public = 1;
   */
  public: InsightSensor[];

  /**
   * @generated from field: repeated crypto.v1.Encrypted private = 2;
   */
  private: Encrypted[];
};

/**
 * Describes the message device.v1.Insight.
 * Use `create(InsightSchema)` to create a new message.
 */
export const InsightSchema: GenMessage<Insight> = /*@__PURE__*/
  messageDesc(file_device_v1_insight, 2);

