// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=.js"
// @generated from file device/v1/urban.proto (package device.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Encrypted } from "../../crypto/v1/encrypted_pb.js";
import { file_crypto_v1_encrypted } from "../../crypto/v1/encrypted_pb.js";
import type { BME280, GPS, ICS43434, SDS011 } from "../../sensor/v1/sensor_pb.js";
import { file_sensor_v1_sensor } from "../../sensor/v1/sensor_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file device/v1/urban.proto.
 */
export const file_device_v1_urban: GenFile = /*@__PURE__*/
  fileDesc("ChVkZXZpY2UvdjEvdXJiYW4ucHJvdG8SCWRldmljZS52MSKpAQoLVXJiYW5TZW5zb3ISHQoDZ3BzGAEgASgLMg4uc2Vuc29yLnYxLkdQU0gAEiMKBmJtZTI4MBgCIAEoCzIRLnNlbnNvci52MS5CTUUyODBIABIjCgZzZHMwMTEYAyABKAsyES5zZW5zb3IudjEuU0RTMDExSAASJwoIaWNzNDM0MzQYBCABKAsyEy5zZW5zb3IudjEuSUNTNDM0MzRIAEIICgZzZW5zb3IiOQoORW5jcnlwdGVkVXJiYW4SJwoHc2Vuc29ycxgBIAMoCzIWLmRldmljZS52MS5VcmJhblNlbnNvciJWCgVVcmJhbhImCgZwdWJsaWMYASADKAsyFi5kZXZpY2UudjEuVXJiYW5TZW5zb3ISJQoHcHJpdmF0ZRgCIAMoCzIULmNyeXB0by52MS5FbmNyeXB0ZWRiBnByb3RvMw", [file_crypto_v1_encrypted, file_sensor_v1_sensor]);

/**
 * @generated from message device.v1.UrbanSensor
 */
export type UrbanSensor = Message<"device.v1.UrbanSensor"> & {
  /**
   * @generated from oneof device.v1.UrbanSensor.sensor
   */
  sensor: {
    /**
     * @generated from field: sensor.v1.GPS gps = 1;
     */
    value: GPS;
    case: "gps";
  } | {
    /**
     * @generated from field: sensor.v1.BME280 bme280 = 2;
     */
    value: BME280;
    case: "bme280";
  } | {
    /**
     * @generated from field: sensor.v1.SDS011 sds011 = 3;
     */
    value: SDS011;
    case: "sds011";
  } | {
    /**
     * @generated from field: sensor.v1.ICS43434 ics43434 = 4;
     */
    value: ICS43434;
    case: "ics43434";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message device.v1.UrbanSensor.
 * Use `create(UrbanSensorSchema)` to create a new message.
 */
export const UrbanSensorSchema: GenMessage<UrbanSensor> = /*@__PURE__*/
  messageDesc(file_device_v1_urban, 0);

/**
 * @generated from message device.v1.EncryptedUrban
 */
export type EncryptedUrban = Message<"device.v1.EncryptedUrban"> & {
  /**
   * @generated from field: repeated device.v1.UrbanSensor sensors = 1;
   */
  sensors: UrbanSensor[];
};

/**
 * Describes the message device.v1.EncryptedUrban.
 * Use `create(EncryptedUrbanSchema)` to create a new message.
 */
export const EncryptedUrbanSchema: GenMessage<EncryptedUrban> = /*@__PURE__*/
  messageDesc(file_device_v1_urban, 1);

/**
 * @generated from message device.v1.Urban
 */
export type Urban = Message<"device.v1.Urban"> & {
  /**
   * @generated from field: repeated device.v1.UrbanSensor public = 1;
   */
  public: UrbanSensor[];

  /**
   * @generated from field: repeated crypto.v1.Encrypted private = 2;
   */
  private: Encrypted[];
};

/**
 * Describes the message device.v1.Urban.
 * Use `create(UrbanSchema)` to create a new message.
 */
export const UrbanSchema: GenMessage<Urban> = /*@__PURE__*/
  messageDesc(file_device_v1_urban, 2);

