// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=.js"
// @generated from file core/v1/message.proto (package core.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Urban } from "../../device/v1/urban_pb.js";
import { file_device_v1_urban } from "../../device/v1/urban_pb.js";
import type { Insight } from "../../device/v1/insight_pb.js";
import { file_device_v1_insight } from "../../device/v1/insight_pb.js";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file core/v1/message.proto.
 */
export const file_core_v1_message: GenFile = /*@__PURE__*/
  fileDesc("ChVjb3JlL3YxL21lc3NhZ2UucHJvdG8SB2NvcmUudjEiFQoETWV0YRINCgVvd25lchgBIAEoDCJ/CgdNZXNzYWdlEh8KCG1ldGFkYXRhGAEgASgLMg0uY29yZS52MS5NZXRhEiEKBXVyYmFuGAIgASgLMhAuZGV2aWNlLnYxLlVyYmFuSAASJQoHaW5zaWdodBgDIAEoCzISLmRldmljZS52MS5JbnNpZ2h0SABCCQoHcGF5bG9hZGIGcHJvdG8z", [file_device_v1_urban, file_device_v1_insight]);

/**
 * @generated from message core.v1.Meta
 */
export type Meta = Message$1<"core.v1.Meta"> & {
  /**
   * @generated from field: bytes owner = 1;
   */
  owner: Uint8Array;
};

/**
 * Describes the message core.v1.Meta.
 * Use `create(MetaSchema)` to create a new message.
 */
export const MetaSchema: GenMessage<Meta> = /*@__PURE__*/
  messageDesc(file_core_v1_message, 0);

/**
 * @generated from message core.v1.Message
 */
export type Message = Message$1<"core.v1.Message"> & {
  /**
   * @generated from field: core.v1.Meta metadata = 1;
   */
  metadata?: Meta | undefined;

  /**
   * @generated from oneof core.v1.Message.payload
   */
  payload: {
    /**
     * @generated from field: device.v1.Urban urban = 2;
     */
    value: Urban;
    case: "urban";
  } | {
    /**
     * @generated from field: device.v1.Insight insight = 3;
     */
    value: Insight;
    case: "insight";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message core.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema: GenMessage<Message> = /*@__PURE__*/
  messageDesc(file_core_v1_message, 1);

