name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check-license:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v7
      - name: Check license
        uses: viperproject/check-license-header@v2
        with:
          path: ./
          config: ./.github/license-check/config.json
          strict: false

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Configure BSR Registry Auth
        run: |
          echo "@buf:registry=https://buf.build/gen/npm/v1/" >> ~/.npmrc
          echo "//buf.build/gen/npm/v1/:_authToken=${{ secrets.BUF_TOKEN }}" >> ~/.npmrc
      - uses: pnpm/setup@v2
      - run: pnpm build 
      - run: docker compose up -d
      - run: pnpm test
      - run: pnpm typecheck
      - run: pnpm lint

#  e2e:
#    needs: unit-tests
#    permissions:
#      contents: read
#      actions: write
#    uses: ./.github/workflows/integration-test.yml
